services:
  - type: web
    name: userbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m userbot.main
    autoDeploy: true
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: SESSION_STRING
        sync: false
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.9.0 